name = "barajitas-api"
main = "src/index.ts"
compatibility_date = "2026-05-01"

[[d1_databases]]
binding = "DB"
database_name = "barajitas-db"
database_id = "dee9e40f-3ac6-4447-9db4-e4b0b16fd53d"

[vars]
ALLOWED_ORIGIN = "https://davecelot.github.io"
JWT_TTL_SECONDS = "2592000"
